# Generated by Django 3.1 on 2021-08-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210827_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_addes',
            new_name='date_added',
        ),
    ]
